### ISSUE TITLE
Usage in production

### ISSUE THREAD

**Issue by nnikushkaa** [patrickjane/libcex#2]
Hi Patrick, thanks for developing this awesome library. is it safe to use in production?

**Comment by patrickjane** [comment]
Hey, you're welcome.
I have developed this library some years ago as part of C++11 experimentations, and never since used it in production environments. From my side, the project never exceeded prototype state. Also, the underlying dependencies to `libevhtp` and `libevent` might now be outdated, and the library is missing support for websockets (see #1 ). 

The functionality, however, had been tested fully/almost fully using unit tests, so the library can be considered complete. You're free to use the library in any way you want (considering the MIT license), however, I probably will be unable to provide support/fixes/changes.

**Comment by nnikushkaa** [comment]
Thanks for your quick reply..
It is a well-written & well-structured library and got many ideas from it.
So the whole library is kinda dead, but your ideas are still alive ;)
